import { z } from 'zod';

export const Category = z.union([
  z.literal('BT01'),
  z.literal('BT02'),
  z.literal('BT03'),
  z.literal('BT04'),
  z.literal('BT05'),
  z.literal('BT06'),
  z.literal('BT07'),
  z.literal('BT08'),
  z.literal('BT09'),
  z.literal('BT10'),
  z.literal('BT11'),
  z.literal('BT12'),
  z.literal('EX01'),
  z.literal('EX02'),
  z.literal('EX03'),
  z.literal('EX04'),
  z.literal('ST01'),
  z.literal('ST02'),
  z.literal('ST03'),
  z.literal('ST04'),
  z.literal('ST05'),
  z.literal('ST06'),
  z.literal('ST07'),
  z.literal('ST08'),
  z.literal('ST09'),
  z.literal('ST10'),
  z.literal('ST11'),
  z.literal('ST12'),
  z.literal('ST13'),
  z.literal('ST14'),
  z.literal('PRO'),
]);

export type Category = z.infer<typeof Category>;
